services:
  - type: web
    name: fittrackpro-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd mk/mk/Fittrack/django_backend && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn fittrack.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: "postgresql://fittrack_user:ZN3chRBveTZqgYSVef9Ku2BIr9sSj7LJ@dpg-dac6bmek1f9s73b7drfg-a.singapore-postgres.render.com/fittrack_db_340o"
      - key: SECRET_KEY
        value: "django-insecure-f#j6)9t+m7117e+t*e!o-iemm@y@-&0$u#&%qpn-&g=p)yoqk3"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: "3.11"
