import os
import sys
import django
from decimal import Decimal

if sys.stdout and hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "fittrack.settings")
django.setup()

from store.models import Category, Product

# Clear existing products before seeding
Product.objects.all().delete()

PRODUCTS = [
    # ---------------- WEIGHTS ----------------
    {
        "name": "Pro Olympic Barbell 20kg",
        "category": "Weights",
        "price": 8999,
        "was_price": 10999,
        "off_percent": 18,
        "description": "Professional 20kg Olympic barbell suitable for strength training and powerlifting.",
        "tag": "BEST SELLER",
        "is_deal": True,
        "is_featured": True,
        "stock": 25,
        "image": "product_images/olympic-barbell-20kg.jpg",
    },
    {
        "name": "Rubber Bumper Plate Set 100kg",
        "category": "Weights",
        "price": 24999,
        "was_price": 29999,
        "off_percent": 17,
        "description": "Premium rubber bumper plate set designed for Olympic lifting.",
        "tag": "HOT DEAL",
        "is_deal": True,
        "is_featured": True,
        "stock": 15,
        "image": "product_images/rubber-bumper-plate-set-100kg.jpg",
    },
    {
        "name": "EZ Curl Bar",
        "category": "Weights",
        "price": 3999,
        "was_price": 4999,
        "off_percent": 20,
        "description": "EZ curl bar for comfortable and effective biceps training.",
        "tag": "POPULAR",
        "is_featured": True,
        "stock": 40,
        "image": "product_images/ez-curl-bar.jpg",
    },
    {
        "name": "Cast Iron Plate Set 50kg",
        "category": "Weights",
        "price": 6999,
        "was_price": 8499,
        "off_percent": 18,
        "description": "Durable cast iron weight plates for home and commercial gyms.",
        "tag": "VALUE",
        "stock": 30,
        "image": "product_images/cast-iron-plate-set-50kg.jpg",
    },
    {
        "name": "Trap Bar / Hex Bar",
        "category": "Weights",
        "price": 10999,
        "was_price": 12999,
        "off_percent": 15,
        "description": "Heavy-duty hex bar for deadlifts, shrugs and functional strength training.",
        "tag": "PRO",
        "stock": 18,
        "image": "product_images/trap-bar-hex-bar.jpg",
    },
    {
        "name": "Olympic Curl Bar with Collars",
        "category": "Weights",
        "price": 4999,
        "was_price": 5999,
        "off_percent": 17,
        "description": "Olympic curl bar supplied with secure spring collars.",
        "tag": "NEW",
        "stock": 35,
        "image": "product_images/olympic-curl-bar-with-collars.jpg",
    },

    # ---------------- RACKS ----------------
    {
        "name": "Heavy Duty Power Rack",
        "category": "Racks",
        "price": 44999,
        "was_price": 54999,
        "off_percent": 18,
        "description": "Heavy-duty power rack for squats, bench press and complete strength workouts.",
        "tag": "BEST SELLER",
        "is_deal": True,
        "is_featured": True,
        "stock": 10,
        "image": "product_images/heavy-duty-power-rack.jpg",
    },
    {
        "name": "Half Rack with Pull-up Bar",
        "category": "Racks",
        "price": 29999,
        "was_price": 34999,
        "off_percent": 14,
        "description": "Compact half rack with integrated pull-up bar.",
        "tag": "POPULAR",
        "stock": 12,
        "image": "product_images/half-rack-with-pullup-bar.jpg",
    },
    {
        "name": "Full Powerlifting Competition Rack",
        "category": "Racks",
        "price": 69999,
        "was_price": 79999,
        "off_percent": 13,
        "description": "Competition-grade powerlifting rack for professional training facilities.",
        "tag": "PRO",
        "is_featured": True,
        "stock": 5,
        "image": "product_images/full-powerlifting-competition-rack.jpg",
    },

    # ---------------- CARDIO ----------------
    {
        "name": "Commercial Treadmill T-9",
        "category": "Cardio",
        "price": 89999,
        "was_price": 109999,
        "off_percent": 18,
        "description": "Commercial treadmill with powerful motor and large running deck.",
        "tag": "BEST SELLER",
        "is_deal": True,
        "is_featured": True,
        "stock": 8,
        "image": "product_images/commercial-treadmill-t9.jpg",
    },
    {
        "name": "Air Rowing Machine",
        "category": "Cardio",
        "price": 44999,
        "was_price": 54999,
        "off_percent": 18,
        "description": "Air resistance rowing machine for full-body cardiovascular workouts.",
        "tag": "HOT",
        "stock": 10,
        "image": "product_images/air-rowing-machine.jpg",
    },
    {
        "name": "Spin Bike Studio Edition",
        "category": "Cardio",
        "price": 32999,
        "was_price": 39999,
        "off_percent": 18,
        "description": "Studio-quality indoor cycling bike with adjustable resistance.",
        "tag": "POPULAR",
        "is_featured": True,
        "stock": 15,
        "image": "product_images/spin-bike-studio-edition.jpg",
    },
    {
        "name": "Commercial Elliptical Trainer",
        "category": "Cardio",
        "price": 74999,
        "was_price": 89999,
        "off_percent": 17,
        "description": "Low-impact elliptical trainer designed for commercial gym use.",
        "tag": "PRO",
        "stock": 7,
        "image": "product_images/commercial-elliptical-trainer.jpg",
    },
    {
        "name": "Curved Manual Treadmill",
        "category": "Cardio",
        "price": 69999,
        "was_price": 79999,
        "off_percent": 13,
        "description": "Self-powered curved treadmill for sprint and HIIT training.",
        "tag": "PREMIUM",
        "is_featured": True,
        "stock": 6,
        "image": "product_images/curved-manual-treadmill.jpg",
    },
    {
        "name": "Spin Bike Home Edition",
        "category": "Cardio",
        "price": 19999,
        "was_price": 24999,
        "off_percent": 20,
        "description": "Affordable indoor spin bike designed for home workouts.",
        "tag": "DEAL",
        "is_deal": True,
        "stock": 25,
        "image": "product_images/spin-bike-home-edition.jpg",
    },
    {
        "name": "Recumbent Exercise Bike",
        "category": "Cardio",
        "price": 35999,
        "was_price": 42999,
        "off_percent": 16,
        "description": "Comfortable recumbent bike for low-impact cardio training.",
        "tag": "COMFORT",
        "stock": 12,
        "image": "product_images/recumbent-exercise-bike.jpg",
    },
    {
        "name": "Stair Climber Step Machine",
        "category": "Cardio",
        "price": 59999,
        "was_price": 69999,
        "off_percent": 14,
        "description": "Professional stair climbing machine for intense cardio sessions.",
        "tag": "PRO",
        "stock": 8,
        "image": "product_images/stair-climber-step-machine.jpg",
    },

    # ---------------- BENCHES ----------------
    {
        "name": "Adjustable FID Bench",
        "category": "Benches",
        "price": 14999,
        "was_price": 17999,
        "off_percent": 17,
        "description": "Flat incline decline adjustable bench for versatile strength workouts.",
        "tag": "BEST SELLER",
        "is_featured": True,
        "stock": 20,
        "image": "product_images/adjustable-fid-bench.jpg",
    },
    {
        "name": "Flat Utility Bench",
        "category": "Benches",
        "price": 6999,
        "was_price": 8499,
        "off_percent": 18,
        "description": "Strong and compact flat utility bench for home gyms.",
        "tag": "VALUE",
        "stock": 30,
        "image": "product_images/flat-utility-bench.jpg",
    },
    {
        "name": "Adjustable Weight Bench Pro",
        "category": "Benches",
        "price": 17999,
        "was_price": 21999,
        "off_percent": 18,
        "description": "Premium adjustable weight bench with multiple backrest positions.",
        "tag": "PRO",
        "stock": 18,
        "image": "product_images/adjustable-weight-bench-pro.jpg",
    },
    {
        "name": "Preacher Curl Bench",
        "category": "Benches",
        "price": 8999,
        "was_price": 10999,
        "off_percent": 18,
        "description": "Dedicated preacher curl bench for focused biceps training.",
        "tag": "POPULAR",
        "stock": 15,
        "image": "product_images/preacher-curl-bench.jpg",
    },

    # ---------------- ACCESSORIES ----------------
    {
        "name": "Premium Cotton Wrist Wraps",
        "category": "Accessories",
        "price": 999,
        "was_price": 1499,
        "off_percent": 33,
        "description": "Premium cotton wrist wraps for additional wrist support.",
        "tag": "DEAL",
        "is_deal": True,
        "stock": 100,
        "image": "product_images/premium-cotton-wrist-wraps.jpg",
    },
    {
        "name": "Resistance Band Set - 5 Levels",
        "category": "Accessories",
        "price": 1499,
        "was_price": 1999,
        "off_percent": 25,
        "description": "Five resistance levels suitable for strength and mobility workouts.",
        "tag": "BEST SELLER",
        "is_featured": True,
        "stock": 80,
        "image": "product_images/resistance-band-set-5-levels.jpg",
    },
    {
        "name": "Adjustable Dumbbell Pair 20kg",
        "category": "Dumbbells",
        "price": 8999,
        "was_price": 10999,
        "off_percent": 18,
        "description": "Space-saving adjustable dumbbell pair with multiple weight settings.",
        "tag": "HOT DEAL",
        "is_deal": True,
        "is_featured": True,
        "stock": 25,
        "image": "product_images/adjustable-dumbbell-pair-20kg.jpg",
    },
    {
        "name": "Kettlebell Set 4kg to 16kg",
        "category": "Kettlebells",
        "price": 7999,
        "was_price": 9999,
        "off_percent": 20,
        "description": "Multi-weight kettlebell set for functional fitness training.",
        "tag": "SET",
        "stock": 20,
        "image": "product_images/kettlebell-set-4kg-to-16kg.jpg",
    },
    {
        "name": "Olympic Weightlifting Platform",
        "category": "Accessories",
        "price": 34999,
        "was_price": 39999,
        "off_percent": 13,
        "description": "Heavy-duty platform designed for Olympic weightlifting.",
        "tag": "PRO",
        "stock": 8,
        "image": "product_images/olympic-weightlifting-platform.jpg",
    },
    {
        "name": "Neoprene Dumbbell Pair 2kg",
        "category": "Dumbbells",
        "price": 999,
        "was_price": 1299,
        "off_percent": 23,
        "description": "Compact neoprene dumbbells ideal for home fitness and aerobics.",
        "tag": "HOME GYM",
        "stock": 60,
        "image": "product_images/neoprene-dumbbell-pair-2kg.jpg",
    },
    {
        "name": "Skipping Rope with Counter",
        "category": "Accessories",
        "price": 799,
        "was_price": 999,
        "off_percent": 20,
        "description": "Speed skipping rope with digital counter for cardio training.",
        "tag": "DEAL",
        "is_deal": True,
        "stock": 100,
        "image": "product_images/skipping-rope-with-counter.jpg",
    },
    {
        "name": "Push-Up Board Training System",
        "category": "Accessories",
        "price": 1299,
        "was_price": 1799,
        "off_percent": 28,
        "description": "Multi-position push-up board for targeted upper-body training.",
        "tag": "POPULAR",
        "stock": 70,
        "image": "product_images/push-up-board-training-system.jpg",
    },
    {
        "name": "Ab Roller Wheel with Knee Pad",
        "category": "Accessories",
        "price": 899,
        "was_price": 1299,
        "off_percent": 31,
        "description": "Ab roller wheel with comfortable knee pad for core training.",
        "tag": "DEAL",
        "is_deal": True,
        "stock": 90,
        "image": "product_images/ab-roller-wheel-with-knee-pad.jpg",
    },
    {
        "name": "Yoga Mat 8mm Anti-Slip",
        "category": "Yoga & Fitness",
        "price": 1499,
        "was_price": 1999,
        "off_percent": 25,
        "description": "Extra-thick anti-slip yoga mat for yoga, stretching and workouts.",
        "tag": "BEST SELLER",
        "is_featured": True,
        "stock": 100,
        "image": "product_images/yoga-mat-8mm-anti-slip.jpg",
    },
    {
        "name": "Weighted Medicine Ball 8kg",
        "category": "Functional Training",
        "price": 2999,
        "was_price": 3999,
        "off_percent": 25,
        "description": "Durable 8kg medicine ball for functional strength training.",
        "tag": "TRAINING",
        "stock": 35,
        "image": "product_images/weighted-medicine-ball-8kg.jpg",
    },
    {
        "name": "Plyometric Jump Box Set",
        "category": "Functional Training",
        "price": 6999,
        "was_price": 8499,
        "off_percent": 18,
        "description": "Adjustable plyometric box set for explosive power training.",
        "tag": "PRO",
        "stock": 15,
        "image": "product_images/plyometric-jump-box-set.jpg",
    },
    {
        "name": "Battle Rope 40ft",
        "category": "Functional Training",
        "price": 3999,
        "was_price": 4999,
        "off_percent": 20,
        "description": "Heavy-duty 40ft battle rope for HIIT and conditioning.",
        "tag": "HIIT",
        "stock": 30,
        "image": "product_images/battle-rope-40ft.jpg",
    },
    {
        "name": "Pull-Up Bar Doorway Mount",
        "category": "Accessories",
        "price": 1999,
        "was_price": 2499,
        "off_percent": 20,
        "description": "Strong doorway-mounted pull-up bar for home workouts.",
        "tag": "HOME GYM",
        "stock": 50,
        "image": "product_images/pull-up-bar-doorway-mount.jpg",
    },
    {
        "name": "Competition Kettlebell 24kg",
        "category": "Kettlebells",
        "price": 3499,
        "was_price": 4499,
        "off_percent": 22,
        "description": "Competition-style 24kg kettlebell for advanced training.",
        "tag": "PRO",
        "stock": 25,
        "image": "product_images/competition-kettlebell-24kg.jpg",
    },

    # ---------------- STORAGE ----------------
    {
        "name": "Vertical Plate Storage Tree",
        "category": "Storage",
        "price": 5999,
        "was_price": 7499,
        "off_percent": 20,
        "description": "Compact vertical storage tree for Olympic weight plates.",
        "tag": "STORAGE",
        "stock": 20,
        "image": "product_images/vertical-plate-storage-tree.jpg",
    },
    {
        "name": "Dumbbell Storage Rack 3 Tier",
        "category": "Storage",
        "price": 8999,
        "was_price": 10999,
        "off_percent": 18,
        "description": "Three-tier dumbbell rack for organized gym storage.",
        "tag": "STORAGE",
        "stock": 15,
        "image": "product_images/dumbbell-storage-rack-3-tier.jpg",
    },

    # ---------------- MACHINES ----------------
    {
        "name": "Sled Push and Pull Trainer",
        "category": "Functional Training",
        "price": 9999,
        "was_price": 12999,
        "off_percent": 23,
        "description": "Heavy-duty sled trainer for pushing and pulling workouts.",
        "tag": "FUNCTIONAL",
        "stock": 12,
        "image": "product_images/sled-push-and-pull-trainer.jpg",
    },
    {
        "name": "Rubber Gym Flooring Roll 10mm",
        "category": "Gym Flooring",
        "price": 4999,
        "was_price": 5999,
        "off_percent": 17,
        "description": "10mm rubber flooring roll designed to protect gym floors.",
        "tag": "GYM ESSENTIAL",
        "stock": 40,
        "image": "product_images/rubber-gym-flooring-roll-10mm.jpg",
    },
    {
        "name": "Functional Cable Crossover Machine",
        "category": "Machines",
        "price": 119999,
        "was_price": 139999,
        "off_percent": 14,
        "description": "Professional cable crossover machine for complete functional training.",
        "tag": "PREMIUM",
        "is_featured": True,
        "stock": 4,
        "image": "product_images/functional-cable-crossover-machine.jpg",
    },
    {
        "name": "Smith Machine with Lat Pulldown",
        "category": "Machines",
        "price": 89999,
        "was_price": 109999,
        "off_percent": 18,
        "description": "Multi-functional Smith machine with integrated lat pulldown system.",
        "tag": "BEST SELLER",
        "is_deal": True,
        "is_featured": True,
        "stock": 5,
        "image": "product_images/smith-machine-with-lat-pulldown.jpg",
    },
    {
        "name": "Professional Leg Press Machine",
        "category": "Machines",
        "price": 99999,
        "was_price": 119999,
        "off_percent": 17,
        "description": "Professional leg press machine for commercial gyms.",
        "tag": "PRO",
        "stock": 4,
        "image": "product_images/professional-leg-press-machine.jpg",
    },
    {
        "name": "Multi Station 8-User Gym",
        "category": "Machines",
        "price": 299999,
        "was_price": 349999,
        "off_percent": 14,
        "description": "Commercial eight-user multi-station gym system.",
        "tag": "COMMERCIAL",
        "is_featured": True,
        "stock": 2,
        "image": "product_images/multi-station-8-user-gym.jpg",
    },
    {
        "name": "Complete Commercial Gym Setup",
        "category": "Gym Packages",
        "price": 599999,
        "was_price": 699999,
        "off_percent": 14,
        "description": "Complete commercial gym setup with professional equipment.",
        "tag": "PREMIUM PACKAGE",
        "is_deal": True,
        "is_featured": True,
        "stock": 2,
        "image": "product_images/complete-commercial-gym-setup.jpg",
    },
    {
        "name": "Seated Chest Press Machine",
        "category": "Machines",
        "price": 79999,
        "was_price": 94999,
        "off_percent": 16,
        "description": "Commercial seated chest press machine for controlled chest training.",
        "tag": "CHEST",
        "stock": 5,
        "image": "product_images/seated-chest-press-machine.jpg",
    },
    {
        "name": "Lat Pulldown and Low Row",
        "category": "Machines",
        "price": 69999,
        "was_price": 84999,
        "off_percent": 18,
        "description": "Dual-function lat pulldown and low row machine.",
        "tag": "BACK",
        "stock": 6,
        "image": "product_images/lat-pulldown-and-low-row.jpg",
    },
    {
        "name": "Seated Leg Extension Machine",
        "category": "Machines",
        "price": 64999,
        "was_price": 79999,
        "off_percent": 19,
        "description": "Commercial leg extension machine for isolated quadriceps training.",
        "tag": "LEGS",
        "stock": 6,
        "image": "product_images/seated-leg-extension-machine.jpg",
    },
    {
        "name": "Assisted Dip and Pull-Up Machine",
        "category": "Machines",
        "price": 84999,
        "was_price": 99999,
        "off_percent": 15,
        "description": "Assisted dip and pull-up machine for progressive upper-body training.",
        "tag": "UPPER BODY",
        "stock": 5,
        "image": "product_images/assisted-dip-and-pull-up-machine.jpg",
    },
    {
        "name": "Luxury Home Gym Package",
        "category": "Gym Packages",
        "price": 249999,
        "was_price": 299999,
        "off_percent": 17,
        "description": "Premium home gym package containing essential strength and cardio equipment.",
        "tag": "LUXURY",
        "is_deal": True,
        "is_featured": True,
        "stock": 5,
        "image": "product_images/luxury-home-gym-package.jpg",
    },
]


def seed_products():
    print("\n========================================")
    print("       FITTRACK PRODUCT SEEDER")
    print("========================================\n")

    added = 0
    skipped = 0

    for data in PRODUCTS:
        category_name = data.pop("category")

        category, _ = Category.objects.get_or_create(
            name=category_name
        )

        product, created = Product.objects.get_or_create(
            name=data["name"],
            defaults={
                "category": category,
                "price": Decimal(str(data["price"])),
                "was_price": Decimal(str(data["was_price"])),
                "off_percent": data["off_percent"],
                "description": data["description"],
                "image": data["image"],
                "tag": data.get("tag"),
                "is_deal": data.get("is_deal", False),
                "is_featured": data.get("is_featured", False),
                "claimed": 0,
                "ends_in_hours": 48,
                "stock": data.get("stock", 0),
            },
        )

        if created:
            added += 1
            print(f"✅ Added: {product.name}")
        else:
            skipped += 1
            print(f"⏭️ Already exists: {product.name}")

    print("\n========================================")
    print(f"✅ Products added : {added}")
    print(f"⏭️ Already existed: {skipped}")
    print(f"📦 Total products : {Product.objects.count()}")
    print("========================================\n")


if __name__ == "__main__":
    seed_products()