# Generated by Django 4.2.14 on 2026-08-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_contactmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
