# Generated by Django 4.2.14 on 2026-08-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_contactmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
