# Generated by Django 5.0.6 on 2026-08-23 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_coupon_discount_order_deal_savings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('return-policy', 'Return Policy'), ('refund-policy', 'Refund Policy'), ('privacy-policy', 'Privacy Policy'), ('disclaimer', 'Disclaimer')], unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PolicySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='📋', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Main paragraph text for this section')),
                ('list_items', models.TextField(blank=True, help_text='Bullet points, one per line')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='store.policy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
