# Generated by Django 5.0.6 on 2026-08-23 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_policy_policysection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.PositiveIntegerField(blank=True, help_text='Specific order item id (optional)', null=True)),
                ('product_name', models.CharField(max_length=200)),
                ('reason', models.CharField(choices=[('changed_mind', 'Changed my mind'), ('better_price', 'Found a better price'), ('wrong_item', 'Received wrong item'), ('defective', 'Item is defective/damaged'), ('not_as_described', 'Not as described'), ('size_issue', 'Size/fit issue'), ('other', 'Other reason')], max_length=30)),
                ('reason_detail', models.TextField(blank=True, help_text='Additional details from user')),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Picked Up', 'Picked Up'), ('Inspected', 'Inspected'), ('Refund Initiated', 'Refund Initiated'), ('Refund Completed', 'Refund Completed'), ('Rejected', 'Rejected')], default='Requested', max_length=20)),
                ('ran_number', models.CharField(blank=True, help_text='Return Authorization Number', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='store.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
