# Generated by Django 5.0.6 on 2026-09-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in INR (from Razorpay)', max_digits=12, null=True),
        ),
    ]
